const data = [
  {
    id: 1,
    productName: "Ab.leno",
    Description:
      "This is is abceddfjsaljf alsjflasjf lj lasjfasjf lafas fafj afja lfja f",
    brand: "Gucci",
    usedFor: "male",
    season: "Winter",
    available: true,
    category: "3MI",
    price: 1200,
    sale: "3%",
    createdDate: "12/12/2023",
    expiry_Date: "12/12/2023",
    rating: 4.2,
    bottlesize: "1ml",
    deliveryTime: "3 Days",
    pic: "abcd",
  },
  {
    id: 2,
    productName: "Eau de Parfum",
    Description: "A luxurious fragrance for the modern man",
    brand: "Gucci",
    usedFor: "male",
    season: "Summer",
    available: true,
    category: "10MI",
    price: 900,
    sale: "5%",
    createdDate: "01/01/2022",
    expiry_Date: "01/01/2024",
    rating: 4.5,
    bottlesize: "2ml",
    deliveryTime: "2 Days",
    pic: "efgh",
  },
  {
    id: 3,
    productName: "Floral Delight",
    Description: "A sweet and feminine fragrance for the modern woman",
    brand: "Chanel",
    usedFor: "female",
    season: "Spring",
    available: true,
    category: "33MI",
    price: 1500,
    sale: "2%",
    createdDate: "03/03/2022",
    expiry_Date: "03/03/2024",
    rating: 4.8,
    bottlesize: "1.5ml",
    deliveryTime: "4 Days",
    pic: "ijkl",
  },
  {
    id: 4,
    productName: "Citrus Burst",
    Description:
      "A refreshing and invigorating fragrance for the active individual",
    brand: "Dior",
    usedFor: "unisex",
    season: "Summer",
    available: true,
    category: "50MI",
    price: 1000,
    sale: "4%",
    createdDate: "06/06/2022",
    expiry_Date: "06/06/2024",
    rating: 4.1,
    bottlesize: "2.5ml",
    deliveryTime: "3 Days",
    pic: "mnop",
  },
  {
    id: 5,
    productName: "Oriental Spice",
    Description: "A rich and exotic fragrance for the sophisticated individual",
    brand: "Tom Ford",
    usedFor: "male",
    season: "Winter",
    available: true,
    category: "100MI",
    price: 1800,
    sale: "1%",
    createdDate: "09/09/2022",
    expiry_Date: "09/09/2024",
    rating: 4.9,
    bottlesize: "1ml",
    deliveryTime: "5 Days",
    pic: "qrst",
  },
  {
    id: 6,
    productName: "Fresh Bloom",
    Description: "A light and airy fragrance for the modern woman",
    brand: "Chanel",
    usedFor: "female",
    season: "Spring",
    available: true,
    category: "50MI",
    price: 1200,
    sale: "3%",
    createdDate: "12/12/2022",
    expiry_Date: "12/12/2024",
    rating: 4.4,
    bottlesize: "1.5ml",
    deliveryTime: "4 Days",
    pic: "uvwx",
  },
  {
    id: 7,
    productName: "Sporty Fresh",
    Description: "A cool and refreshing fragrance for the active individual",
    brand: "Dior",
    usedFor: "unisex",
    season: "Summer",
    available: true,
    category: "3MI",
    price: 800,
    sale: "6%",
    createdDate: "03/03/2023",
    expiry_Date: "03/03/2025",
    rating: 4.3,
    bottlesize: "2ml",
    deliveryTime: "3 Days",
    pic: "yzab",
  },
  {
    id: 8,
    productName: "Elegant Rose",
    Description: "A sophisticated and romantic fragrance for the modern woman",
    brand: "Gucci",
    usedFor: "female",
    season: "Spring",
    available: true,
    category: "10MI",
    price: 1400,
    sale: "2%",
    createdDate: "06/06/2023",
    expiry_Date: "06/06/2025",
    rating: 4.7,
    bottlesize: "1ml",
    deliveryTime: "4 Days",
    pic: "cdef",
  },
  {
    id: 9,
    productName: "Woody Notes",
    Description: "A rugged and earthy fragrance for the modern man",
    brand: "Tom Ford",
    usedFor: "male",
    season: "Winter",
    available: true,
    category: "100MI",
    price: 1600,
    sale: "1%",
    createdDate: "09/09/2023",
    expiry_Date: "09/09/2025",
    rating: 4.8,
    bottlesize: "2.5ml",
    deliveryTime: "5 Days",
    pic: "ghij",
  },
  {
    id: 11,
    productName: "Ocean Breeze",
    Description:
      "A refreshing and invigorating fragrance for the active individual",
    brand: "Dior",
    usedFor: "unisex",
    season: "Summer",
    available: true,
    category: "50MI",
    price: 1100,
    sale: "5%",
    createdDate: "12/12/2023",
    expiry_Date: "12/12/2025",
    rating: 4.6,
    bottlesize: "2ml",
    deliveryTime: "3 Days",
    pic: "klmn",
  },
  {
    id: 12,
    productName: "Sensual Musk",
    Description: "A seductive and alluring fragrance for the modern woman",
    brand: "Gucci",
    usedFor: "female",
    season: "Winter",
    available: true,
    category: "50MI",
    price: 1300,
    sale: "2%",
    createdDate: "03/03/2024",
    expiry_Date: "03/03/2026",
    rating: 4.5,
    bottlesize: "1.5ml",
    deliveryTime: "4 Days",
    pic: "opqr",
  },
  {
    id: 13,
    productName: "Citrus Zing",
    Description: "A bright and uplifting fragrance for the modern man",
    brand: "Tom Ford",
    usedFor: "male",
    season: "Summer",
    available: true,
    category: "10MI",
    price: 1500,
    sale: "1%",
    createdDate: "06/06/2024",
    expiry_Date: "06/06/2026",
    rating: 4.9,
    bottlesize: "2.5ml",
    deliveryTime: "5 Days",
    pic: "stuv",
  },

  {
    id: 15,
    productName: "Woody Essence",
    Description: "A rugged and earthy fragrance for the modern man",
    brand: "Dior",
    usedFor: "male",
    season: "Winter",
    available: true,
    category: "3MI",
    price: 1400,
    sale: "2%",
    createdDate: "12/12/2024",
    expiry_Date: "12/12/2026",
    rating: 4.8,
    bottlesize: "2ml",
    deliveryTime: "5 Days",
    pic: "abcd",
  },
  {
    id: 16,
    productName: "Fresh Cut",
    Description: "A light and airy fragrance for the modern woman",
    brand: "Gucci",
    usedFor: "female",
    season: "Spring",
    available: true,
    category: "50MI",
    price: 1100,
    sale: "5%",
    createdDate: "03/03/2025",
    expiry_Date: "03/03/2027",
    rating: 4.6,
    bottlesize: "1.5ml",
    deliveryTime: "4 Days",
    pic: "efgh",
  },
  {
    id: 17,
    productName: "Oriental Nights",
    Description: "A rich and exotic fragrance for the sophisticated individual",
    brand: "Tom Ford",
    usedFor: "unisex",
    season: "Winter",
    available: true,
    category: "3MI",
    price: 1600,
    sale: "1%",
    createdDate: "06/06/2025",
    expiry_Date: "06/06/2027",
    rating: 4.9,
    bottlesize: "2.5ml",
    deliveryTime: "5 Days",
    pic: "ijkl",
  },
  {
    id: 18,
    productName: "Floral Bouquet",
    Description: "A sweet and feminine fragrance for the modern woman",
    brand: "Chanel",
    usedFor: "female",
    season: "Spring",
    available: true,
    category: "10MI",
    price: 1300,
    sale: "2%",
    createdDate: "09/09/2025",
    expiry_Date: "09/09/2027",
    rating: 4.7,
    bottlesize: "1ml",
    deliveryTime: "4 Days",
    pic: "mnop",
  },
  {
    id: 19,
    productName: "Sporty Fresh",
    Description: "A cool and refreshing fragrance for the active individual",
    brand: "Dior",
    usedFor: "unisex",
    season: "Summer",
    available: true,
    category: "50MI",
    price: 1000,
    sale: "6%",
    createdDate: "12/12/2025",
    expiry_Date: "12/12/2027",
    rating: 4.3,
    bottlesize: "2ml",
    deliveryTime: "3 Days",
    pic: "qrst",
  },
  {
    id: 20,
    productName: "Elegant Rose",
    Description: "A sophisticated and romantic fragrance for the modern woman",
    brand: "Gucci",
    usedFor: "female",
    season: "Spring",
    available: true,
    category: "50MI",
    price: 1400,
    sale: "2%",
    createdDate: "03/03/2026",
    expiry_Date: "03/03/2028",
    rating: 4.8,
    bottlesize: "1.5ml",
    deliveryTime: "4 Days",
    pic: "uvwx",
  },
];

export default data;
